language: csharp
solution: TravisCITest.sln
install:
  - nuget restore TravisCITest.sln
  - nuget install xunit.runners -Version 2.0.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release TravisCITest.sln
  - mono ./testrunner/xunit.runners.2.0.0/tools/xunit.console.clr4.exe ./TravisCITest/TravisCITest.Test/bin/Release/TravisCITest.Test.dll
