language: csharp
solution: TravisCITest.sln
install:
  - nuget restore TravisCITest.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release TravisCITest.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./TravisCITest/TravisCITest.Test/bin/Release/TravisCITest.Test.dll
