language: csharp
solution: TravisCITest.sln
install:
  - nuget restore TravisCITest.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release TravisCITest.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./TravisCITest/TravisCITest.Test/bin/Release/TravisCITest.Test.dll
